# DDL for MUDAC schema
# Warning: executing this script will delete and replace all tables and delete all data

USE MUDAC;

DROP TABLE IF EXISTS MEMBER_INFORMATION_ST;
DROP TABLE IF EXISTS MEDICAL_TRN_ST;
DROP TABLE IF EXISTS MEDICAL_TAR_ST;
DROP TABLE IF EXISTS CONFINEMENT_TRN_ST;
DROP TABLE IF EXISTS CONFINEMENT_TAR_ST;
DROP TABLE IF EXISTS RX_TRN_ST;
DROP TABLE IF EXISTS RX_TAR_ST;
DROP TABLE IF EXISTS LABRESULT_TRN_ST;
DROP TABLE IF EXISTS LABRESULT_TAR_ST;
DROP TABLE IF EXISTS LU_DIAGNOSIS_ST;
DROP TABLE IF EXISTS LU_PROCEDURE_ST;
DROP TABLE IF EXISTS ABNL_CD_ST;
DROP TABLE IF EXISTS AHFSCLSS;
DROP TABLE IF EXISTS DRG_ST;
DROP TABLE IF EXISTS POS_ST;
DROP TABLE IF EXISTS STATE_ST;
DROP TABLE IF EXISTS PROVAT_ST;
DROP TABLE IF EXISTS RVNU_CD_ST;

CREATE TABLE `MEMBER_INFORMATION_ST` (
	`PATID` int(9) NOT NULL
	,`GENDER` varchar(10) DEFAULT NULL
	,`YEAR_OF_BIRTH` int(4) DEFAULT NULL
	,`STATE` varchar(2) DEFAULT NULL
	,PRIMARY KEY (`PATID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `MEDICAL_TRN_ST` (
  `ID` INT NOT NULL auto_increment
  ,`PATID` INT NOT NULL
  ,`CLMID` VARCHAR(19) NOT NULL
  ,`CONF_ID` VARCHAR(21) NULL
  ,`POS` VARCHAR(5) NULL
  ,`DRG` VARCHAR(5) NULL
  ,`PROVCAT` VARCHAR(5) NULL
  ,`RVNU_CD` VARCHAR(4) NULL
  ,`PROC_CD` VARCHAR(21) NULL
  ,`DIAG1` VARCHAR(7) NULL
  ,`DIAG2` VARCHAR(7) NULL
  ,`DIAG3` VARCHAR(7) NULL
  ,`DIAG4` VARCHAR(7) NULL
  ,`DIAG5` VARCHAR(7) NULL
  ,`PROC1` VARCHAR(7) NULL
  ,`PROC2` VARCHAR(7) NULL
  ,`PROC3` VARCHAR(7) NULL
  ,`PROC4` VARCHAR(7) NULL
  ,`PROC5` VARCHAR(7) NULL
  ,`DAYS_FROM_DIAG` int(15) NULL
   , PRIMARY KEY (`ID`)
   , FOREIGN KEY FK_PAT_TRN(PATID) REFERENCES MEMBER_INFORMATION_ST(PATID)
   #, FOREIGN KEY FK_CONF(CONF_ID) REFERENCES CONF_ID(CONFINEMENT_ST)
)  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `MEDICAL_TAR_ST` (
  `ID` INT NOT NULL auto_increment
  ,`PATID` INT NOT NULL
  ,`CLMID` VARCHAR(19) NOT NULL
  ,`CONF_ID` VARCHAR(21) NULL
  ,`POS` VARCHAR(5) NULL
  ,`DRG` VARCHAR(5) NULL
  ,`PROVCAT` VARCHAR(5) NULL
  ,`RVNU_CD` VARCHAR(4) NULL
  ,`PROC_CD` VARCHAR(21) NULL
  ,`DIAG1` VARCHAR(7) NULL
  ,`DIAG2` VARCHAR(7) NULL
  ,`DIAG3` VARCHAR(7) NULL
  ,`DIAG4` VARCHAR(7) NULL
  ,`DIAG5` VARCHAR(7) NULL
  ,`PROC1` VARCHAR(7) NULL
  ,`PROC2` VARCHAR(7) NULL
  ,`PROC3` VARCHAR(7) NULL
  ,`PROC4` VARCHAR(7) NULL
  ,`PROC5` VARCHAR(7) NULL
  ,`DAYS_FROM_DIAG` int(15) NULL
   , PRIMARY KEY (`ID`)
   , FOREIGN KEY FK_PAT_TAR(PATID) REFERENCES MEMBER_INFORMATION_ST(PATID)
   #, FOREIGN KEY FK_CONF(CONF_ID) REFERENCES CONF_ID(CONFINEMENT_ST)
)  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE `CONFINEMENT_TRN_ST` (
  `ID` INT NOT NULL auto_increment
  ,`PATID` INT(8) NOT NULL
  ,`CONF_ID` VARCHAR(8) NOT NULL
  ,`STD_COST` DECIMAL(10,8) NOT NULL
  ,`DRG` INT(8) NOT NULL
  ,`POS` VARCHAR(5) NULL
  ,`DIAG1` VARCHAR(7) NULL
  ,`DIAG2` VARCHAR(7) NULL
  ,`DIAG3` VARCHAR(7) NULL
  ,`DIAG4` VARCHAR(7) NULL
  ,`DIAG5` VARCHAR(7) NULL
  ,`PROC1` VARCHAR(7) NULL
  ,`PROC2` VARCHAR(7) NULL
  ,`PROC3` VARCHAR(7) NULL
  ,`PROC4` VARCHAR(7) NULL
  ,`PROC5` VARCHAR(7) NULL
  ,`DAYS_FROM_DIAG` INT(15) NULL
  ,`DISCHARGE_DAYS_FROM_DIAG` INT(15) NULL
  ,PRIMARY KEY (`ID`)

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `CONFINEMENT_TAR_ST` (
  `ID` INT NOT NULL auto_increment
  ,`PATID` INT(8) NOT NULL
  ,`CONF_ID` VARCHAR(8) NOT NULL
  ,`STD_COST` DECIMAL(10,8) NOT NULL
  ,`DRG` INT(8) NOT NULL
  ,`POS` VARCHAR(5) NULL
  ,`DIAG1` VARCHAR(7) NULL
  ,`DIAG2` VARCHAR(7) NULL
  ,`DIAG3` VARCHAR(7) NULL
  ,`DIAG4` VARCHAR(7) NULL
  ,`DIAG5` VARCHAR(7) NULL

  ,`PROC1` VARCHAR(7) NULL
  ,`PROC2` VARCHAR(7) NULL
  ,`PROC3` VARCHAR(7) NULL
  ,`PROC4` VARCHAR(7) NULL
  ,`PROC5` VARCHAR(7) NULL
  ,`DAYS_FROM_DIAG` INT(15) NULL
  ,`DISCHARGE_DAYS_FROM_DIAG` INT(15) NULL
  ,PRIMARY KEY (`ID`)

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `RX_TAR_ST` (
  `ID` INT NOT NULL auto_increment
  ,`PAT_ID` INT(8) NOT NULL
  ,`CLM_ID` VARCHAR(8) NOT NULL
  ,`AHFSCLSS` VARCHAR(8) NOT NULL
  ,`DAYS_SUP` INT(8) NULL
  ,`QUANTITY` INT(8) NULL
  ,`STD_COST` NUMERIC(8) NULL
  ,`DAYS_FROM_DIAG` INT(15) NULL
  ,PRIMARY KEY (`ID`)

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `RX_TRN_ST` (
  `ID` INT NOT NULL auto_increment
  ,`PAT_ID` INT(8) NOT NULL
  ,`CLM_ID` VARCHAR(8) NOT NULL
  ,`AHFSCLSS` VARCHAR(8) NOT NULL
  ,`DAYS_SUP` INT(8) NULL
  ,`QUANTITY` INT(8) NULL
  ,`STD_COST` NUMERIC(8) NULL
  ,`DAYS_FROM_DIAG` INT(15) NULL
  ,PRIMARY KEY (`ID`)

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE `LABRESULT_TAR_ST` (
  `ID` INT NOT NULL auto_increment
  ,`PAT_ID` INT(8) NOT NULL
  ,`ABNL_CD` VARCHAR(2) NOT NULL
  ,`ANALYTICSEQ` VARCHAR(2) NOT NULL
  ,`HI_NRML` DECIMAL(10,8) NULL
  ,`LABCLMID` VARCHAR(19) NULL
  ,`LOINC_CD` VARCHAR(7) NULL
  ,`LOW_NRML` DECIMAL(10,8) NULL
  ,`PROC_CD` VARCHAR(7) NULL
  ,`RSLT_NBR` DECIMAL(10,8) NULL

  ,`RSLT_TXT` VARCHAR(18) NULL
  ,`RSLT_UNIT_NM` VARCHAR(18) NULL
  ,`DAYS_FROM_DIAG` INT(15) NULL
  ,PRIMARY KEY (`ID`)

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE `LABRESULT_TRN_ST` (
  `ID` INT NOT NULL auto_increment
  ,`PAT_ID` INT(8) NOT NULL
  ,`ABNL_CD` VARCHAR(2) NOT NULL
  ,`ANALYTICSEQ` VARCHAR(2) NOT NULL
  ,`HI_NRML` DECIMAL(10,8) NULL
  ,`LABCLMID` VARCHAR(19) NULL
  ,`LOINC_CD` VARCHAR(7) NULL
  ,`LOW_NRML` DECIMAL(10,8) NULL
  ,`PROC_CD` VARCHAR(7) NULL
  ,`RSLT_NBR` DECIMAL(10,8) NULL

  ,`RSLT_TXT` VARCHAR(18) NULL
  ,`RSLT_UNIT_NM` VARCHAR(18) NULL
  ,`DAYS_FROM_DIAG` INT(15) NULL
  ,PRIMARY KEY (`ID`)

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `LU_DIAGNOSIS_ST` (
  `DIAG_ID` VARCHAR(10) NOT NULL
  ,`DIAG_DESC` VARCHAR(100) NOT NULL
  ,`DIAG_FST3_CD` VARCHAR(3) NOT NULL
  ,`DIAG_FST3_DESC` VARCHAR(35) NULL
  ,`DIAG_FST4_CD` VARCHAR(3) NULL
  ,`DIAG_FST4_DESC` VARCHAR(35) NULL
  ,`GDR_SPEC_CD` VARCHAR(5) NULL
  ,`MDC_CD_DESC` VARCHAR(75) NULL
  ,`MDC_CODE` VARCHAR(10) NULL
  ,`ICD_VER_CD` VARCHAR(2) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `LU_PROCEDURE_ST` (
  `CATEGORY_DTL_CD` VARCHAR(5) NOT NULL
  ,`CATEGORY_DTL_CODE_DESC` VARCHAR(50) NOT NULL
  ,`CATEGORY_GENL_CD` VARCHAR(5) NOT NULL
  ,`CATEGORY_GENL_CODE_DESC` VARCHAR(5) NOT NULL
  ,`PROC_CD` VARCHAR(10) NULL
  ,`PROC_DESC` VARCHAR(100) NULL
  ,`PROC_END_DATE` DECIMAL(10,5) NULL
  ,`PROC_TYP_CD` VARCHAR(5) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `ABNL_CD_ST` (
  `ABNL_CD` VARCHAR(5) NOT NULL
  ,`ABNL_DESC` VARCHAR(120) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `AHFSCLSS_ST` (
  `AHFSCLSS` VARCHAR(10) NOT NULL
  ,`AHFSCLSS_DESC` VARCHAR(120) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `DRG_ST` (
  `DRG` VARCHAR(10) NOT NULL
  ,`DRG_DESC` VARCHAR(120) NOT NULL
  ,`EFF_DATE` DATETIME NULL
  ,`END_DATE` DATETIME NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `POS_ST` (
  `POS` VARCHAR(10) NOT NULL
  ,`POS_DESC` VARCHAR(120) NOT NULL
  ,`POS_CAT` VARCHAR(120) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `STATE_ST` (
  `STATE` VARCHAR(10) NOT NULL
  ,`STATE_DESC` VARCHAR(120) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `PROVCAT_ST` (
  `PROVCAT` VARCHAR(10) NOT NULL
  ,`PROVCAT_DESC` VARCHAR(120) NOT NULL
  ,`CATGY_ROL_UP_1_DESC` VARCHAR(120) NULL
  ,`CATGY_ROL_UP_2_DESC` VARCHAR(120) NULL
  ,`CATGY_ROL_UP_3_DESC` VARCHAR(120) NULL
  ,`CATGY_ROL_UP_4_DESC` VARCHAR(120) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `RVNU_CD_ST` (
  `RVNU_CD` VARCHAR(10) NOT NULL
  ,`RVNU_DESC` VARCHAR(120) NOT NULL
  ,`RVNU_CATGY_DESC` VARCHAR(120) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;